# Generated by Django 3.1.1 on 2020-10-18 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackathon', '0007_auto_20201017_1148'),
    ]

    operations = [
        migrations.AddField(
            model_name='hackathon',
            name='theme',
            field=models.CharField(max_length=264, null=True),
        ),
        migrations.AlterField(
            model_name='hackathon',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='hackathon',
            name='display_name',
            field=models.CharField(default='', max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='hackathon',
            name='end_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='hackathon',
            name='start_date',
            field=models.DateTimeField(null=True),
        ),
    ]
