# Generated by Django 3.1.1 on 2020-10-18 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackathon', '0007_auto_20201017_1148'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hackproject',
            old_name='collab_link',
            new_name='deployed_url',
        ),
        migrations.RenameField(
            model_name='hackproject',
            old_name='github_link',
            new_name='github_url',
        ),
        migrations.AddField(
            model_name='hackproject',
            name='share_permission',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='hackproject',
            name='speaker_name',
            field=models.CharField(default='', max_length=225),
        ),
    ]
