# Generated by Django 3.1.1 on 2020-10-20 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hackathon', '0012_remove_hackproject_created_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hackproject',
            name='mentor',
        ),
    ]
