# Generated by Django 3.1.1 on 2020-10-24 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackathon', '0017_auto_20201024_1431'),
    ]

    operations = [
        migrations.AddField(
            model_name='hackathon',
            name='status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
