# Generated by Django 3.1.1 on 2020-10-26 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hackathon', '0017_auto_20201025_2140'),
        ('hackathon', '0017_auto_20201026_1312'),
    ]

    operations = [
    ]
