# Generated by Django 3.1.1 on 2020-10-28 23:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hackathon', '0021_hackathon_participants'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hackathon',
            name='judges',
        ),
        migrations.AddField(
            model_name='hackathon',
            name='judges',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hackathon_judges', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='hackathon',
            name='participants',
        ),
        migrations.AddField(
            model_name='hackathon',
            name='participants',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hackathon_participants', to=settings.AUTH_USER_MODEL),
        ),
    ]
