# Generated by Django 3.1.1 on 2020-10-29 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackathon', '0021_merge_20201029_1407'),
    ]

    operations = [
        migrations.AddField(
            model_name='hackathon',
            name='judging_status',
            field=models.CharField(choices=[('not_yet_started', "Hasn't started"), ('open', 'Open'), ('closed', 'Closed')], default='not_yet_started', max_length=16),
        ),
    ]
