# Generated by Django 3.1.1 on 2020-11-03 21:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hackathon', '0022_auto_20201028_2308'),
        ('hackathon', '0022_hackathon_judging_status'),
    ]

    operations = [
    ]
