# Generated by Django 3.1.1 on 2020-11-03 21:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hackathon', '0023_merge_20201103_2114'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hackathon',
            name='judges',
        ),
        migrations.AddField(
            model_name='hackathon',
            name='judges',
            field=models.ManyToManyField(blank=True, related_name='hackathon_judges', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='hackathon',
            name='participants',
        ),
        migrations.AddField(
            model_name='hackathon',
            name='participants',
            field=models.ManyToManyField(blank=True, related_name='hackathon_participants', to=settings.AUTH_USER_MODEL),
        ),
    ]
