# Generated by Django 3.1.3 on 2021-01-19 00:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hackathon', '0026_hackprojectscorecategory_hackathon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hackawardcategory',
            name='winning_project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hackathon.hackproject'),
        ),
    ]
