# Generated by Django 3.1.3 on 2021-01-18 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackathon', '0029_auto_20210117_1352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hackproject',
            name='technologies_used',
            field=models.CharField(default='', help_text='Add any technologies that were used for this project', max_length=1024),
        ),
    ]
