# Generated by Django 3.1.3 on 2021-01-20 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hackathon', '0028_auto_20210119_2352'),
        ('hackathon', '0031_merge_20210118_1524'),
    ]

    operations = [
    ]
