# Generated by Django 3.1.3 on 2021-01-28 17:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hackathon', '0032_merge_20210120_1141'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hackathon',
            options={'verbose_name': 'Hackathon', 'verbose_name_plural': 'Hackathons'},
        ),
        migrations.AlterModelOptions(
            name='hackawardcategory',
            options={'verbose_name': 'Hack Award Category', 'verbose_name_plural': 'Hack Award Categories'},
        ),
        migrations.RemoveField(
            model_name='hackawardcategory',
            name='hackathon',
        ),
        migrations.RemoveField(
            model_name='hackawardcategory',
            name='winning_project',
        ),
        migrations.AddField(
            model_name='hackawardcategory',
            name='ranking',
            field=models.IntegerField(null=True),
        ),
        migrations.CreateModel(
            name='HackAward',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hackawards', to=settings.AUTH_USER_MODEL)),
                ('hack_award_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='award', to='hackathon.hackawardcategory')),
                ('hackathon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='awards', to='hackathon.hackathon')),
                ('winning_project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hackathon.hackproject')),
            ],
            options={
                'verbose_name': 'Hack Award',
                'verbose_name_plural': 'Hack Awards',
                'unique_together': {('hackathon', 'hack_award_category')},
            },
        ),
    ]
