# Generated by Django 3.1.3 on 2021-02-05 13:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_auto_20210205_1300'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hackathon', '0034_hackathon_hackathon_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='hackathon',
            name='organisation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hackathons', to='accounts.organisation'),
        ),
        migrations.AlterField(
            model_name='hackathon',
            name='organiser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organised_hackathons', to=settings.AUTH_USER_MODEL),
        ),
    ]
