LMS_LEVELS = {
    "programme_preliminaries": 1,
    "programming_paradigms": 1,
    "html_essentials": 1,
    "css_essentials": 1,
    "user_centric_frontend_development": 1,
    "comparative_programming_languages_essentials": 2,
    "javascript_essentials": 2,
    "interactive_frontend_development": 2,
    "python_essentials": 3,
    "practical_python": 3,
    "data_centric_development": 3,
    "backend_development": 3,
    "full_stack_frameworks_with_django": 4,
    "alumni": 5,
    "staff": 6,
}