version: "3.4"

services:
  hackathon-app:
    image: hackathon-app
    # Do NOT use in actual production setup
    environment: 
      DEVELOPMENT: 1
      SECRET_KEY: "your_secret_key_here"
      SITE_NAME: "*"
      SLACK_ENABLED: "True"
      SHOWCASE_SPOTLIGHT_NUMBER: 5
      SUPPORT_EMAIL: community@codeinstitute.net
      DBHOST: mysql
      DBPORT: 3306
      DBNAME: hackathons
      DBUSER: hackathon_user
      DBPASS: gummyball
    volumes:
      - ./src/hackathon/:/hackathon-app/hackathon/
    ports:
      - "8000:8000"

  mysql:
    image: docker.io/mysql:5.6.36
    command: mysqld --character-set-server=utf8 --collation-server=utf8_general_ci
    # Do NOT use for production
    environment:
      MYSQL_ROOT_PASSWORD: gummyball
      MYSQL_DATABASE: hackathons
      MYSQL_USER: hackathon_user
      MYSQL_PASSWORD: gummyball
    volumes:
      - ./data/mysql:/var/lib/mysql
  
  nginx:
    image: nginx
    volumes:
      - ${PWD}/nginx/:/etc/nginx/conf.d/
    ports:
      - "80:80"
    #  - "443:443"
    depends_on:
      - hackathon-app
