# Generated by Django 3.1.3 on 2021-01-23 11:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hackathon', '0032_merge_20210120_1141'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Showcase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('display_name', models.CharField(default='', max_length=255)),
                ('showcase_image', models.TextField(blank=True, default='', help_text='Image displayed on the project showcase page to promote the project. Img should ideally be 500x800px.')),
                ('is_public', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_showcases', to=settings.AUTH_USER_MODEL)),
                ('hack_project', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='showcase', to='hackathon.hackproject')),
                ('showcase_participants', models.ManyToManyField(related_name='showcases', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Project Showcase',
                'verbose_name_plural': 'Project Showcases',
            },
        ),
    ]
