# Generated by Django 3.1.1 on 2020-10-22 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisation',
            name='display_name',
            field=models.CharField(blank=True, choices=[('code_institute', 'Code Institute')], default='Code Institute', max_length=100),
        ),
    ]
