# Generated by Django 3.1.1 on 2020-10-23 23:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organisation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(default='Code Institute', max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='customuser',
            name='organisation',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_organisation', to='accounts.organisation'),
        ),
    ]
