# Generated by Django 3.1.1 on 2020-10-21 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20201020_2042'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='organisation',
            field=models.CharField(blank=True, default='Code Institute', max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('deleted', 'Deleted')], default='published', max_length=9),
            preserve_default=False,
        ),
    ]
