# Generated by Django 3.1.1 on 2020-10-22 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20201022_1354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisation',
            name='display_name',
            field=models.CharField(blank=True, default='Code Institute', max_length=100),
        ),
    ]
