# Generated by Django 3.1.3 on 2021-01-16 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20210115_1706'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='email_is_public',
            field=models.BooleanField(default=False, help_text='Enabling this will let other users see your email address; profile needs to be set to public as well'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='profile_is_public',
            field=models.BooleanField(default=False, help_text='Enabling this will let other users see your profile inlcuding your name, about, website, where you are on the course'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='slack_display_name_is_public',
            field=models.BooleanField(default=False, help_text='Enabling this will let other users see your Slack display name; profile needs to be set to public as well'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='website_url',
            field=models.URLField(default='', help_text='Website, GitHub or Linkedin URL', max_length=255),
        ),
    ]
