# Generated by Django 3.1.3 on 2021-01-16 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20210116_1717'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='profile_image',
            field=models.TextField(blank=True, default='', help_text='Text field to store base64 encoded profile image content.'),
        ),
    ]
