# Generated by Django 3.1.3 on 2021-01-18 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_remove_customuser_slack_display_name_is_public'),
        ('accounts', '0006_auto_20210111_2242'),
    ]

    operations = [
    ]
