# Generated by Django 3.1.6 on 2021-03-19 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_remove_customuser_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_external',
            field=models.BooleanField(default=False, help_text='Set to True if a user signs up through an external registration link'),
        ),
    ]
