# Generated by Django 3.1.12 on 2021-10-11 19:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_customuser_is_external'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='current_lms_module',
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(max_length=80)),
                ('level', models.IntegerField()),
                ('admin_only', models.BooleanField(default=False)),
                ('organisation', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='statuses', to='accounts.organisation')),
            ],
            options={
                'verbose_name': 'Status',
                'verbose_name_plural': 'Statuses',
            },
        ),
        migrations.AddField(
            model_name='customuser',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.status'),
        ),
    ]
