# Generated by Django 3.1.13 on 2022-12-19 14:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_customuser_timezone'),
    ]

    operations = [
        migrations.CreateModel(
            name='SlackSiteSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enable_welcome_emails', models.BooleanField(default=True)),
                ('communication_channel_type', models.CharField(choices=[('slack_private_channel', 'Private Slack Channel'), ('other', 'Other')], default='slack_private_channel', max_length=50)),
                ('slack_admins', models.ManyToManyField(related_name='slacksitesettings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Slack Site Settings',
                'verbose_name_plural': 'Slack Site Settings',
            },
        ),
    ]
