# Generated by Django 3.1.12 on 2021-10-11 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_auto_20211011_1946'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='status',
            options={'ordering': ('display_order',), 'verbose_name': 'Status', 'verbose_name_plural': 'Statuses'},
        ),
        migrations.AddField(
            model_name='status',
            name='display_order',
            field=models.IntegerField(default=1),
        ),
    ]
