# Generated by Django 3.1.13 on 2023-01-04 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_emailtemplate'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='emailtemplate',
            options={'verbose_name': 'Email Template', 'verbose_name_plural': 'Email Templates'},
        ),
        migrations.AlterField(
            model_name='emailtemplate',
            name='template_name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
