# Generated by Django 3.1.13 on 2023-01-23 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_auto_20230104_1655'),
    ]

    operations = [
        migrations.AddField(
            model_name='slacksitesettings',
            name='remove_admin_from_channel',
            field=models.BooleanField(default=True, help_text='The user linked to the ADMIN_BOT_TOKEN will automatically be added to any new channels. If this is ticked, the user will be removed from private team channels if they are not part of the team, facilitator or the slack admins'),
        ),
    ]
