# Generated by Django 3.1.13 on 2025-02-05 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_auto_20230104_1655'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='current_course',
            field=models.CharField(choices=[('', 'Select Current Course'), ('L3', 'The Level 3 Diploma in Software Development (L3)'), ('5P', 'The 5 project Diploma in Software Development Course (5P)'), ('4P', 'The 4 project Diploma in Software Development Course (4P)'), ('FSBC', 'The 16 Week Full Stack Developer Bootcamp (BC)'), ('DATABC', 'The 16 Week Data-Analytics Bootcamp (DBC)')], default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='current_lms_module',
            field=models.CharField(choices=[('', 'Select Learning Stage'), ('no_coding_experience', 'No coding experience'), ('just_starting', 'Just starting the course'), ('mid_course', 'In the middle of the course'), ('end_course', 'At the end of the course'), ('graduated', 'Graduated'), ('dev_duties', 'Working with some development duties'), ('working_dev', 'Working as a developer'), ('guest_judge', 'Guest judge'), ('guest_facilitator', 'Guest facilitator'), ('staff', 'Staff')], default='', max_length=50),
        ),
    ]
