# Generated by Django 3.1.13 on 2024-10-11 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_slacksitesettings_remove_admin_from_channel'),
    ]

    operations = [
        migrations.AddField(
            model_name='slacksitesettings',
            name='use_hackathon_slack_admins',
            field=models.BooleanField(default=False),
        ),
    ]
