# Generated by Django 3.1.13 on 2025-02-17 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_auto_20250214_1439'),
        ('accounts', '0022_auto_20250206_1702'),
    ]

    operations = [
    ]
