# Generated by Django 3.1.13 on 2025-02-17 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_merge_20250217_0913'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='dropoffs',
            field=models.IntegerField(default=0, help_text='Number of times a user has dropped off from a hackathon'),
        ),
    ]
