# Generated by Django 3.1.13 on 2025-02-19 14:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hackathon', '0056_hackathon_badge_url'),
        ('accounts', '0024_customuser_dropoffs'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='dropped_off_hackathon',
            field=models.ForeignKey(blank=True, help_text='The hackathon that the user dropped off from', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dropped_off_users', to='hackathon.hackathon'),
        ),
    ]
