# Generated by Django 3.1.1 on 2020-10-15 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=120, null=True)),
                ('speaker_name', models.CharField(blank=True, max_length=300, null=True)),
                ('repo_url', models.URLField(max_length=1024)),
                ('deployed_url', models.URLField(max_length=1024)),
            ],
        ),
    ]
