# Generated by Django 3.1.8 on 2021-05-11 15:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hackathon', '0042_hackteam_communication_channel'),
        ('showcase', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShowcaseSiteSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_by_category', models.CharField(choices=[('random', 'Random Order'), ('hackathon_date_desc', 'Hackathon Date in Descending Order'), ('hackathon_date_asc', 'Hackathon Date in Ascending Order'), ('alphabetical_desc', 'Alphabetical by Project Name in Descending Order'), ('alphabetical_asc', 'Alphabetical by Project Name in Ascending Order')], default='random', max_length=255)),
                ('feature_selection', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='showcase_featured_hackathons', to='hackathon.hackathon')),
                ('hackathons', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='showcase_hackathons', to='hackathon.hackathon')),
            ],
            options={
                'verbose_name': 'Showcase Site Settings',
                'verbose_name_plural': 'Showcase Site Settings',
            },
        ),
    ]
