# Generated by Django 3.1.8 on 2021-05-12 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackathon', '0042_hackteam_communication_channel'),
        ('showcase', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShowcaseSiteSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_by_category', models.CharField(choices=[('?', 'Random Order'), ('-created', 'Showcase Created Date in Descending Order'), ('created', 'Showcase Created Date in Ascending Order'), ('-updated', 'Showcase Updated Date in Descending Order'), ('updated', 'Showcase Updated Date in Ascending Order'), ('-display_name', 'Alphabetical by Project Name in Descending Order'), ('display_name', 'Alphabetical by Project Name in Ascending Order')], default='random', max_length=255)),
                ('spotlight_number', models.IntegerField(default=5)),
                ('projects_per_page', models.IntegerField(default=5)),
                ('featured_hackathons', models.ManyToManyField(related_name='showcase_featured_hackathons', to='hackathon.Hackathon')),
                ('hackathons', models.ManyToManyField(related_name='showcase_hackathons', to='hackathon.Hackathon')),
            ],
            options={
                'verbose_name': 'Project Showcase Site Settings',
                'verbose_name_plural': 'Project Showcase Site Settings',
            },
        ),
    ]
