# Generated by Django 3.1.8 on 2021-09-07 11:27

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0002_showcasesitesettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='showcase',
            name='hash',
            field=models.UUIDField(default=uuid.uuid4, editable=False, null=True),
        ),
    ]
