# Generated by Django 3.1.8 on 2021-05-11 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackathon', '0042_hackteam_communication_channel'),
        ('showcase', '0002_showcasesitesettings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='showcasesitesettings',
            name='feature_selection',
        ),
        migrations.AddField(
            model_name='showcasesitesettings',
            name='feature_selection',
            field=models.ManyToManyField(related_name='showcase_featured_hackathons', to='hackathon.Hackathon'),
        ),
        migrations.RemoveField(
            model_name='showcasesitesettings',
            name='hackathons',
        ),
        migrations.AddField(
            model_name='showcasesitesettings',
            name='hackathons',
            field=models.ManyToManyField(related_name='showcase_hackathons', to='hackathon.Hackathon'),
        ),
    ]
