# Generated by Django 3.1.8 on 2021-05-12 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0003_auto_20210511_1557'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='showcasesitesettings',
            options={'verbose_name': 'Project Showcase Site Settings', 'verbose_name_plural': 'Project Showcase Site Settings'},
        ),
        migrations.RenameField(
            model_name='showcasesitesettings',
            old_name='feature_selection',
            new_name='featured_hackathons',
        ),
        migrations.AlterField(
            model_name='showcasesitesettings',
            name='order_by_category',
            field=models.CharField(choices=[('?', 'Random Order'), ('-created', 'Showcase Created Date in Descending Order'), ('created', 'Showcase Created Date in Ascending Order'), ('-updated', 'Showcase Updated Date in Descending Order'), ('updated', 'Showcase Updated Date in Ascending Order'), ('-display_name', 'Alphabetical by Project Name in Descending Order'), ('display_name', 'Alphabetical by Project Name in Ascending Order')], default='random', max_length=255),
        ),
    ]
