# Generated by Django 3.1.8 on 2021-09-07 11:28

from django.db import migrations
import uuid


def gen_uuid(apps, schema_editor):
    Showcase = apps.get_model('showcase', 'Showcase')
    for row in Showcase.objects.all():
        row.hash = uuid.uuid4()
        row.save(update_fields=['hash'])


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0003_showcase_hash'),
    ]

    operations = [
        migrations.RunPython(gen_uuid, reverse_code=migrations.RunPython.noop),
    ]
