# Generated by Django 3.1.8 on 2021-09-07 11:28

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0004_auto_20210907_1128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='showcase',
            name='hash',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
