# Generated by Django 3.1.13 on 2022-08-05 16:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Competency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('display_name', models.CharField(default='', max_length=255)),
                ('is_visible', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_competencies', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Competency',
                'verbose_name_plural': 'Competencies',
            },
        ),
        migrations.CreateModel(
            name='CompetencyAssessment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('is_visible', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='competency_assessment', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Competency Self Assessment',
                'verbose_name_plural': 'User Competency Self Assessments',
            },
        ),
        migrations.CreateModel(
            name='CompetencyDifficulty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('display_name', models.CharField(default='', max_length=255, unique=True)),
                ('numeric_difficulty', models.FloatField(default=1.0)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_competency_difficulties', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Competency Difficulty',
                'verbose_name_plural': 'Competency Difficulties',
            },
        ),
        migrations.CreateModel(
            name='CompetencyAssessmentRating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('rating', models.CharField(blank=True, choices=[('want_to_know', 'Want to know about it'), ('learning', 'Learning about it right now'), ('know_it', 'I know about this')], default='', max_length=50, null=True)),
                ('competency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competency_assessment_ratings', to='competencies.competency')),
                ('user_assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competencies', to='competencies.competencyassessment')),
            ],
            options={
                'verbose_name': 'Competency Self Assessment',
                'verbose_name_plural': 'Competency Self Assessments',
            },
        ),
        migrations.AddField(
            model_name='competency',
            name='perceived_difficulty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competencies', to='competencies.competencydifficulty'),
        ),
    ]
