# Generated by Django 3.1.13 on 2022-08-05 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competencies', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='competencydifficulty',
            options={'verbose_name': 'Competency Difficulty', 'verbose_name_plural': 'Competency Difficulties'},
        ),
        migrations.AlterField(
            model_name='competencydifficulty',
            name='display_name',
            field=models.CharField(default='', max_length=255, unique=True),
        ),
    ]
