# Generated by Django 3.1.13 on 2022-08-08 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competencies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competencyassessmentrating',
            name='rating',
            field=models.CharField(blank=True, choices=[('no_knowledge', 'I have no knowledge'), ('want_to_know', 'Want to know about it'), ('learning', 'Learning about it right now'), ('know_it', 'I know about this')], default='', max_length=50, null=True),
        ),
    ]
