# Generated by Django 3.1.12 on 2021-10-01 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartnershipRequestEmailSiteSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_email', models.CharField(max_length=255)),
                ('to_emails', models.TextField(default='[]', help_text='This should be a list of emails (e.g. ["email1", ...]. Default: []')),
                ('subject', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Partnership Request Email Site Settings',
                'verbose_name_plural': 'Partnership Request Email Site Settings',
            },
        ),
    ]
