# Generated by Django 3.1.1 on 2020-10-25 13:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20201024_0008'),
        ('hackathon', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hackathon',
            name='organisation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hackathon_organisation', to='accounts.organisation'),
        ),
    ]
