# Generated by Django 3.1.1 on 2020-10-15 20:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hackathon', '0002_auto_20201015_1936'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hackawardcategory',
            options={'verbose_name_plural': 'Hack award categories'},
        ),
        migrations.CreateModel(
            name='HackTeam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('display_name', models.CharField(default='', max_length=254)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hackteam_created_by', to=settings.AUTH_USER_MODEL)),
                ('participants', models.ManyToManyField(related_name='hackteam', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='HackProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('display_name', models.CharField(default='', max_length=255)),
                ('description', models.TextField()),
                ('github_link', models.CharField(default='', max_length=255)),
                ('collab_link', models.CharField(default='', max_length=255)),
                ('submission_time', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hackproject_created_by', to=settings.AUTH_USER_MODEL)),
                ('mentor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hackproject_mentor', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]