# Generated by Django 3.1.1 on 2020-10-16 19:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hackathon', '0004_auto_20201015_2224'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hackprojectscorecategory',
            name='score',
        ),
        migrations.AddField(
            model_name='hackprojectscore',
            name='hackprojectscorecategory',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='hackathon.hackprojectscorecategory'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='hackathon',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='hackawardcategory',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='hackawardcategory',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hackawardcategories', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='hackproject',
            name='collab_link',
            field=models.URLField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='hackproject',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='hackproject',
            name='github_link',
            field=models.URLField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='hackprojectscore',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='hackprojectscore',
            name='score',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='hackprojectscorecategory',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='hackteam',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
