# Generated by Django 3.1.1 on 2020-10-16 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hackathon', '0005_auto_20201016_1951'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hackprojectscore',
            old_name='hackprojectscorecategory',
            new_name='hack_project_score_category',
        ),
    ]