# Generated by Django 3.1.1 on 2020-10-18 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackathon', '0008_hackprojectscorecategory_highest_score'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hackprojectscorecategory',
            old_name='highest_score',
            new_name='max_score',
        ),
        migrations.AddField(
            model_name='hackprojectscorecategory',
            name='min_score',
            field=models.IntegerField(default=1),
        ),
    ]
