# Generated by Django 3.1.1 on 2020-10-21 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackathon', '0009_auto_20201018_1829'),
    ]

    operations = [
        migrations.AddField(
            model_name='hackathon',
            name='organisation',
            field=models.CharField(blank=True, default='Code Institute', max_length=100),
        ),
    ]
