# Generated by Django 3.1.1 on 2020-10-22 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hackathon', '0009_auto_20201018_1829'),
        ('hackathon', '0008_auto_20201018_1301'),
    ]

    operations = [
    ]
