# Generated by Django 3.1.1 on 2020-10-23 23:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('hackathon', '0010_merge_20201022_2224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hackathon',
            name='description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='hackathon',
            name='display_name',
            field=models.CharField(default='', max_length=254),
        ),
        migrations.AlterField(
            model_name='hackathon',
            name='end_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='hackathon',
            name='start_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='hackathon',
            name='theme',
            field=models.CharField(default='', max_length=264),
            preserve_default=False,
        ),
    ]
