# Generated by Django 3.1.1 on 2020-10-21 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackathon', '0010_hackathon_organisation'),
    ]

    operations = [
        migrations.AddField(
            model_name='hackathon',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('deleted', 'Deleted')], default='draft', max_length=9),
        ),
    ]
