# Generated by Django 3.1.1 on 2020-10-20 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hackathon', '0011_auto_20201020_1948'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hackproject',
            name='created_by',
        ),
    ]
