# Generated by Django 3.1.1 on 2020-10-24 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hackathon', '0015_auto_20201020_1955'),
        ('hackathon', '0011_auto_20201024_0035'),
    ]

    operations = [
    ]
