# Generated by Django 3.1.1 on 2020-10-30 12:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20201026_1312'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hackathon', '0016_merge_20201030_1245'),
    ]

    operations = [
        migrations.AddField(
            model_name='hackathon',
            name='judging_status',
            field=models.CharField(choices=[('not_yet_started', "Hasn't started"), ('open', 'Open'), ('closed', 'Closed')], default='not_yet_started', max_length=16),
        ),
        migrations.AddField(
            model_name='hackathon',
            name='organisation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hackathon_organisation', to='accounts.organisation'),
        ),
        migrations.AddField(
            model_name='hackathon',
            name='participants',
            field=models.ManyToManyField(blank=True, related_name='hackathon_participants', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='hackathon',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('deleted', 'Deleted')], default='draft', max_length=10),
        ),
        migrations.AlterField(
            model_name='hackproject',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hackproject', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='hackprojectscore',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hackprojectscores', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='hackprojectscore',
            name='judge',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
