# Generated by Django 3.1.1 on 2020-10-25 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackathon', '0018_hackathon_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hackathon',
            name='status',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
