# Generated by Django 3.1.1 on 2020-10-26 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hackathon', '0018_merge_20201026_1722'),
        ('hackathon', '0019_auto_20201025_2022'),
    ]

    operations = [
    ]
