# Generated by Django 3.1.1 on 2020-10-29 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hackathon', '0020_merge_20201026_2056'),
        ('hackathon', '0018_auto_20201025_1933'),
    ]

    operations = [
    ]
