# Generated by Django 3.1.1 on 2020-10-29 21:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hackathon', '0021_hackathon_participants'),
        ('hackathon', '0022_hackathon_judging_status'),
    ]

    operations = [
    ]
