# Generated by Django 3.1.3 on 2021-01-11 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackathon', '0024_auto_20201103_2114'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hackteam',
            options={'verbose_name': 'Hack Team', 'verbose_name_plural': 'Hack Teams'},
        ),
        migrations.AlterField(
            model_name='hackathon',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('registration_open', 'Registration Open'), ('hack_in_progress', 'Hackathon In Progress'), ('judging', 'Judging'), ('finished', 'Hackathon Finished'), ('deleted', 'Deleted')], default='draft', max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='hackteam',
            unique_together={('display_name', 'hackathon')},
        ),
    ]
