# Generated by Django 3.1.3 on 2021-01-13 22:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hackathon', '0024_auto_20201103_2114'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hackteam',
            options={'verbose_name': 'Hack Team', 'verbose_name_plural': 'Hack Teams'},
        ),
        migrations.AlterUniqueTogether(
            name='hackteam',
            unique_together={('display_name', 'hackathon')},
        ),
    ]
