# Generated by Django 3.1.3 on 2021-01-15 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackathon', '0025_auto_20210113_2249'),
    ]

    operations = [
        migrations.AddField(
            model_name='hackproject',
            name='technologies_used',
            field=models.CharField(default='', max_length=1024),
        ),
    ]
