# Generated by Django 3.1.3 on 2021-01-19 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackathon', '0027_auto_20210119_0045'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hackprojectscorecategory',
            name='hackathon',
        ),
        migrations.AddField(
            model_name='hackathon',
            name='score_categories',
            field=models.ManyToManyField(blank=True, related_name='hackathon_score_categories', to='hackathon.HackProjectScoreCategory'),
        ),
    ]
