# Generated by Django 3.1.3 on 2021-01-16 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hackathon', '0027_auto_20210116_1652'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hackproject',
            old_name='screenshot_image_url',
            new_name='screenshot_url',
        ),
    ]
