# Generated by Django 3.1.3 on 2021-01-18 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hackathon', '0030_auto_20210118_1220'),
        ('hackathon', '0025_auto_20210111_2242'),
    ]

    operations = [
    ]
