# Generated by Django 3.1.3 on 2021-02-08 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hackathon', '0035_auto_20210205_1300'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hackathon',
            name='judging_status',
        ),
    ]
