# Generated by Django 3.1.3 on 2021-02-24 15:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hackathon', '0037_hackathon_teamsize'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hackathon',
            name='judges',
            field=models.ManyToManyField(blank=True, related_name='judged_hackathons', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='hackathon',
            name='participants',
            field=models.ManyToManyField(blank=True, related_name='participated_hackathons', to=settings.AUTH_USER_MODEL),
        ),
    ]
