# Generated by Django 3.1.3 on 2021-02-24 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hackathon', '0038_auto_20210224_1521'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hackathon',
            old_name='teamsize',
            new_name='team_size',
        ),
    ]
