# Generated by Django 3.1.3 on 2021-02-25 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackathon', '0039_auto_20210224_1850'),
    ]

    operations = [
        migrations.AddField(
            model_name='hackathon',
            name='tag_line',
            field=models.CharField(default='', help_text='Short description which will be displayed in the Hackathon List view.', max_length=254),
        ),
        migrations.AlterField(
            model_name='hackathon',
            name='description',
            field=models.TextField(help_text='Longer description which will be displayed in the Hackathon Detail view. Usually includes schedule and other details.'),
        ),
    ]
