# Generated by Django 3.1.8 on 2021-05-21 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackathon', '0042_hackteam_communication_channel'),
    ]

    operations = [
        migrations.AddField(
            model_name='hackathon',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
    ]
