# Generated by Django 3.1.8 on 2021-07-17 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackathon', '0043_hackathon_is_public'),
    ]

    operations = [
        migrations.AddField(
            model_name='hackathon',
            name='max_participants',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='hackathon',
            name='theme',
            field=models.CharField(default='', max_length=264),
        ),
    ]
