# Generated by Django 3.1.12 on 2021-10-21 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackathon', '0044_auto_20210717_1654'),
    ]

    operations = [
        migrations.AddField(
            model_name='hackprojectscorecategory',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
