# Generated by Django 3.1.13 on 2022-12-19 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackathon', '0046_auto_20220113_1350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hackathon',
            name='is_public',
            field=models.BooleanField(default=True),
        ),
    ]
