# Generated by Django 3.1.13 on 2022-01-17 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackathon', '0046_auto_20220113_1350'),
    ]

    operations = [
        migrations.AddField(
            model_name='hackathon',
            name='channel_prefix',
            field=models.CharField(blank=True, help_text="Only use lowercase and dash ('-') for spaces", max_length=255, null=True),
        ),
    ]
