# Generated by Django 3.1.13 on 2022-12-19 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackathon', '0047_auto_20221219_1421'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hackteam',
            name='communication_channel',
            field=models.CharField(blank=True, default='', help_text='Usually a link to the Private Slack Channel, but can be a link to something else.', max_length=255),
        ),
    ]
