# Generated by Django 3.1.13 on 2022-01-19 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackathon', '0047_hackathon_channel_prefix'),
    ]

    operations = [
        migrations.AddField(
            model_name='hackathon',
            name='channel_url',
            field=models.CharField(blank=True, help_text='Url', max_length=255, null=True),
        ),
    ]
