# Generated by Django 3.1.13 on 2024-05-10 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackathon', '0048_auto_20221219_1655'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('description', models.TextField(blank=True)),
            ],
        ),
    ]
