# Generated by Django 3.1.13 on 2023-01-23 12:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hackathon', '0048_auto_20221219_1655'),
    ]

    operations = [
        migrations.AddField(
            model_name='hackathon',
            name='channel_admins',
            field=models.ManyToManyField(blank=True, related_name='administered_channels', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='hackathon',
            name='channel_name',
            field=models.CharField(blank=True, help_text="Only use lowercase and dash ('-') for spaces", max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='hackathon',
            name='channel_url',
            field=models.CharField(blank=True, help_text='Url', max_length=255, null=True),
        ),
    ]
