# Generated by Django 3.1.13 on 2022-01-20 10:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hackathon', '0048_hackathon_channel_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='hackathon',
            name='channel_admins',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='administered_channels', to=settings.AUTH_USER_MODEL),
        ),
    ]
