# Generated by Django 3.1.13 on 2022-01-20 10:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hackathon', '0049_hackathon_channel_admins'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hackathon',
            name='channel_admins',
        ),
        migrations.AddField(
            model_name='hackathon',
            name='channel_admins',
            field=models.ManyToManyField(blank=True, null=True, related_name='administered_channels', to=settings.AUTH_USER_MODEL),
        ),
    ]
