# Generated by Django 3.1.13 on 2024-05-10 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackathon', '0049_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
