# Generated by Django 3.1.13 on 2024-05-10 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackathon', '0050_auto_20240510_1722'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='end_date',
            new_name='end',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='start_date',
            new_name='start',
        ),
        migrations.RemoveField(
            model_name='event',
            name='description',
        ),
        migrations.AddField(
            model_name='event',
            name='calendar_id',
            field=models.CharField(default='1', max_length=50),
        ),
        migrations.AddField(
            model_name='event',
            name='category',
            field=models.CharField(default='time', max_length=50),
        ),
        migrations.AddField(
            model_name='event',
            name='due_date_class',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
