# Generated by Django 3.1.13 on 2022-01-20 10:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hackathon', '0050_auto_20220120_1052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hackathon',
            name='channel_admins',
            field=models.ManyToManyField(blank=True, related_name='administered_channels', to=settings.AUTH_USER_MODEL),
        ),
    ]
