# Generated by Django 3.1.13 on 2024-09-12 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hackathon', '0051_auto_20240911_1306'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hackathon',
            old_name='google_registration_form',
            new_name='registration_form',
        ),
    ]
