# Generated by Django 3.1.13 on 2024-05-16 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackathon', '0051_auto_20240510_1728'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='isReadOnly',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='title',
            field=models.CharField(max_length=500),
        ),
    ]
