# Generated by Django 3.1.13 on 2022-01-26 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hackathon', '0051_auto_20220120_1053'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hackathon',
            old_name='channel_prefix',
            new_name='channel_name',
        ),
    ]
