# Generated by Django 3.1.13 on 2024-05-16 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackathon', '0052_auto_20240516_1847'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='category',
        ),
        migrations.RemoveField(
            model_name='event',
            name='due_date_class',
        ),
        migrations.AddField(
            model_name='event',
            name='body',
            field=models.TextField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='event',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
