# Generated by Django 3.1.13 on 2024-09-12 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackathon', '0052_auto_20240912_1324'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hackathon',
            name='is_register',
        ),
        migrations.AddField(
            model_name='hackathon',
            name='allow_external_registrations',
            field=models.BooleanField(default=False),
        ),
    ]
