# Generated by Django 3.1.13 on 2024-10-04 15:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hackathon', '0053_auto_20240912_1527'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('body', models.TextField(default='', max_length=500)),
                ('isReadOnly', models.BooleanField(default=True)),
                ('webinar_link', models.URLField(blank=True, null=True)),
                ('webinar_code', models.CharField(blank=True, max_length=50, null=True)),
                ('hackathon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='hackathon.hackathon')),
            ],
        ),
    ]
