# Generated by Django 3.1.13 on 2024-05-16 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackathon', '0053_auto_20240516_1850'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='category',
            field=models.CharField(default='task', max_length=50),
        ),
    ]
