# Generated by Django 3.1.13 on 2024-05-16 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackathon', '0054_event_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='category',
            field=models.CharField(default='time', max_length=50),
        ),
    ]
