# Generated by Django 3.1.13 on 2024-05-21 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackathon', '0055_auto_20240516_2100'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='google_calendar_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
