# Generated by Django 3.1.13 on 2025-02-14 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackathon', '0055_remove_event_isreadonly'),
    ]

    operations = [
        migrations.AddField(
            model_name='hackathon',
            name='badge_url',
            field=models.URLField(blank=True, default='', help_text='Link to the badge image.'),
        ),
    ]
