# Generated by Django 3.1.13 on 2024-09-10 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackathon', '0056_event_google_calendar_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='presentations_intro_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='zoom_intro_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
