# Generated by Django 3.1.13 on 2024-09-10 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hackathon', '0057_auto_20240910_2006'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='presentations_intro_link',
            new_name='zoom_presentations_link',
        ),
    ]
