# Generated by Django 3.1.13 on 2024-09-10 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hackathon', '0058_auto_20240910_2008'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='zoom_intro_link',
        ),
        migrations.RemoveField(
            model_name='event',
            name='zoom_presentations_link',
        ),
    ]
