# Generated by Django 3.1.13 on 2024-09-15 14:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hackathon', '0059_auto_20240910_2010'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='hackathon',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='hackathon.hackathon'),
            preserve_default=False,
        ),
    ]
