# Generated by Django 3.1.13 on 2024-09-15 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hackathon', '0060_event_hackathon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='calendar_id',
        ),
    ]
