# Generated by Django 3.1.13 on 2024-09-15 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hackathon', '0061_remove_event_calendar_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='category',
        ),
    ]
