# Generated by Django 3.1.13 on 2024-09-15 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hackathon', '0062_remove_event_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='google_calendar_link',
            new_name='webinar_link',
        ),
    ]
