# Generated by Django 3.1.13 on 2024-09-16 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackathon', '0063_auto_20240915_1858'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='webinar_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
