# Generated by Django 3.1.13 on 2024-09-16 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackathon', '0064_event_webinar_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='webinar_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
