# Generated by Django 3.1.1 on 2020-10-25 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20201023_2006'),
        ('accounts', '0003_auto_20201023_1201'),
    ]

    operations = [
    ]
