# Generated by Django 3.1.3 on 2021-01-18 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_customuser_profile_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='slack_display_name_is_public',
        ),
    ]
