# Generated by Django 3.1.3 on 2021-02-05 13:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_merge_20210118_1524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='organisation',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='accounts.organisation'),
        ),
    ]
