from django.urls import path
from teams.views import change_teams
from .views import (
    list_hackathons,
    create_hackathon,
    update_hackathon,
    delete_hackathon,
    enroll_toggle,
    judging,
    check_projects_scores,
    view_hackathon,
    update_hackathon_status,
    change_awards,
    judge_teams,
    assign_mentors,
    view_hackathon_public,
    hackathon_events,
    delete_event,
    hackathon_events_endpoint,
    change_event,
)


urlpatterns = [
    path('', list_hackathons, name="hackathon-list"),
    path("<int:hackathon_id>/team/<int:team_id>/judging/",
         judging, name="judging"),
    path("<int:hackathon_id>/final_score/", check_projects_scores,
         name="final_score"),
    path("<int:hackathon_id>/change_teams/", change_teams,
         name="change_teams"),
    path("<int:hackathon_id>/awards/", change_awards, name="awards"),
    path("create_hackathon", create_hackathon, name='create_hackathon'),
    path("<int:hackathon_id>/", view_hackathon,
         name='view_hackathon'),
    path("public/<int:hackathon_id>/", view_hackathon_public,
         name='view_hackathon_public'),
    path("<int:hackathon_id>/update/", update_hackathon,
         name="update_hackathon"),
    path("<int:hackathon_id>/update_hackathon_status/",
         update_hackathon_status, name="update_hackathon_status"),
    path("<int:hackathon_id>/delete/", delete_hackathon,
         name="delete_hackathon"),
    path('enroll/', enroll_toggle, name='enroll_toggle'),
    path('<int:hackathon_id>/judge_teams/', judge_teams,
         name="judge_teams"),
    path('<int:hackathon_id>/assign_mentors/', assign_mentors,
         name="assign_mentors"),
    path('hackathon/<int:hackathon_id>/event/', change_event,
          name='change_event'),
    path('hackathon/<int:hackathon_id>/event/<int:event_id>/', change_event,
          name='change_event'),
    path('hackathon/<int:hackathon_id>/events/', hackathon_events, 
         name='hackathon_events'),
    path('hackathon/<int:hackathon_id>/event/<int:event_id>/delete/', delete_event, 
         name='delete_event'),  
    path('<int:hackathon_id>/events_endpoint/', hackathon_events_endpoint, 
         name='hackathon_events_endpoint'),       
]
