# Generated by Django 3.1.1 on 2020-10-22 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0002_resource_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='description',
            field=models.TextField(default='', max_length=400),
        ),
    ]
