# Generated by Django 3.1.1 on 2020-10-23 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254)),
                ('link', models.URLField()),
                ('description', models.TextField(default='', max_length=400)),
            ],
        ),
    ]
