# Generated by Django 3.1.1 on 2020-10-22 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='description',
            field=models.TextField(blank=True, max_length=800, null=True),
        ),
    ]
